# Generated by Django 4.2.6 on 2023-10-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0002_pasient_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasient',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
