# Generated by Django 4.2.6 on 2023-10-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0003_pasient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasient',
            name='pasient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/patient_photos'),
        ),
    ]
