# Generated by Django 4.2.6 on 2023-10-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0006_dailybloodpressuredata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailybloodpressuredata',
            old_name='patient',
            new_name='patientID',
        ),
    ]
