# Generated by Django 4.2.6 on 2023-10-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0008_rename_patientid_dailybloodpressuredata_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
