# Generated by Django 4.2.6 on 2023-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0009_delete_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybloodpressuredata',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
