# Generated by Django 4.2.6 on 2023-11-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0012_dailyoxygensaturationdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybloodpressuredata',
            name='oxygen_saturation',
        ),
    ]
